### ISSUE TITLE
Címkézés Githubban

### ISSUE THREAD

**Issue by gerezs** [DelightSolutions/frappe-feedback#10]
Hi, biztos tudjátok, de leírom, mert találkoztunk ezzel:
próbálunk címkét rendelni issuekhoz, de nem tudunk, pedig lehet ez nektek nagy segítség lenne (Android / iOS / Admin). (Tudom, h a githubon a bejelentőknek erre nincs lehetőségük, csak azt hittem a Ti kérésetek volt, h címkézzük fel nektek az issuekat...)

**Comment by tthbalazs** [comment]
Beállítottuk a jogosultságokat, most már minden issue jobb oldalán látszanak a label beállítások.
