### ISSUE TITLE
Távolság a listaelem alatt - hogyan férjen ki egy sorban?

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#100]
A lista alatt megjelent a távolság, de így nem fér ki a sor. A cél: legyen egy sorban.

Ezt javasoljuk:
- A csillag szót vegyük ki, hagyjuk el
- A csillag ikon menjen a 4,3 után
- A távolság így legyen: 3888m Vagyis: nem kell a "-re" 
- Ha kétszámjegyű az ajánlatok száma, akkor istudjon kiférni

**Comment by duroakos** [comment]
erről legyél kedves egy screenshotot csatolni meg hogy milyen készülék.

**Comment by paneksandor** [comment]
Így néz ki Android a606-on

![screenshot_2016-02-26-12-24-16 1](https://cloud.githubusercontent.com/assets/16239437/13351008/1869c624-dc84-11e5-82f9-8f243ee2d147.png)

**Comment by duroakos** [comment]
Köszi

**Comment by duroakos** [comment]
Levesszük a "csillag" és a "-re" feliratokat. Annyi elég lesz.
