### ISSUE TITLE
Aktív akció adatlap nem jelenik meg, az adatlap oldalról nem elérhető

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#103]
Ez lehet, h ugyanaz, mint a #46 ez esetben zárjátok légyszi.

Létrehoztam a "Mostantól minden ingyen van" című Akció adatlapot (amely aktív, időben érvényes), de nem jelenik meg az Akció listámban. 
Viszont megjelenik az akcióhoz kapcsolódó hely adatlapján az ikonon, hogy van aktuális akció. Ide kattintva azonban a Nincs találat fogad. (New York Étel- és Salátabár)
(Android, Lenovi a606)

Ha a létrehozott akció adatlap inaktív, akkor a hely adatlapján nem jelenik meg, hogy a hely akció listájának linkje. (Ez korábbi hiba volt, de most már jól megy)

A többi tesztelő telefonokon az Akciók listában több akciót láttam, mint az enyémen, pedig nem töröltem semmit. 

Egy másik Lenovo a606-os gépen kétszer is megjelent ugyanaz az akció a listában.

**Comment by duroakos** [comment]
az akciók kezelésével kapcsolat voltak valóban érdekes anomáliák.
ezek javítva lettek.
