### ISSUE TITLE
A változások frissítése adminból

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#105]
Ha majd a rendes működésben chachelve lesznek az appok oldalai, az adminban rögzített módosításokat ki tudjuk egyből frissíteni a saját telefonunkon? (Vagy a kettőnek nincs köze egymáshoz?)

**Comment by duroakos** [comment]
ezt a kérdést valahogy át fogalmazod újra, mert nem igazán értem. (persze lehet hogy még túl hétfő van)

**Comment by paneksandor** [comment]
Az éles működés idején, ha adminban módosítunk egy adatlapot, az frissítés után látszik majd az appban? Mi számít frissítésnek: a visszalépés a nyitóra? az app bezárása, kinyitása?

**Comment by duroakos** [comment]
jelenleg indításkor töltődik be újra a szerkesztői ajánlatok és az adott pillanatban értelmezett cimke lista. emiatt lehet hogy egykét menet közben aktivált címke nem jelenik meg a listában, vagy nem megfelelő színnel.
