### ISSUE TITLE
Holnap értékesítői tréning - lesz-e addig új verzió?

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#108]
Ákos, holnap 8.30-tól értékesítői tréninget tartok, és ezen szeretném kivetítve nemutatni az appot. Most azonban épp leállós állapotban van az Android. Lesz-e este új verziótok, vagy készüljek másképp a tréningre?

**Comment by duroakos** [comment]
Ma estére nem ígérek új verziót.
Viszont a leállósságának az okát szerveroldalon orvosoltuk.
Egy újraindítás után mindennek flottul kell mennie. De azért egy B-verzióként ha most néhány működésközbeni képet előkészítessz a holnpai prezihez akkor semmiféle kellemetlen meglepetés nem érhet benneteket.

**Comment by paneksandor** [comment]
Köszi, ma áttettük szerdára, így nincs sietség...
