### ISSUE TITLE
Az aktív, de még nem aktuális akció megjelenik az adatlap és lista Akciószámlálón

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#110]
Létrehozok egy új akciót, ami aktív, de a kezdési dátuma még nem jött el.
Az Akciók listában - helyesen - nem jelenik meg.
Viszont a hozzá tartozó hely adatlapján az Akció ikonon olyan szám jelenik meg, amiben ez az akció is benne van. Kattintva viszont ez a még nem aktuális akció nincs a listában.
És megjelenik a hely listaeleme alatti akciószámlálóban is.
(Ha inaktív és még nem aktuális az akció, akkor nem jelenik meg egyik számlálóban sem.)

**Comment by duroakos** [comment]
Ezzel nem értek egyet.

Létrehozunk egy akciót, és aktívra állítjuk. Onnantól mindenki láthassa.
Hiszen ha péntek este lesz egy akció 9 től. akkor nem csak péntek este 9től tudjak róla. 
Hanem amikortól meg lett hirdetve.

**Comment by paneksandor** [comment]
Visszavontam....

**Comment by duroakos** [comment]
Lezártam.
