### ISSUE TITLE
A régebben létrehozott akcióim megjelentek, de az új nem

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#111]
A korábban létrehozott 2 akcióm ("Mostantól minden ingyen van" és "Semmi sincs ingyen") a javítás nyomán megjelent az Akciók listában!

Ezen felbuzdulva létrehoztam egy új akciót, ami aktív, aktuális (A "New York Étel- és Salátabár" helyhez van kötve), de ez nem kerül bele a listába.

**Comment by duroakos** [comment]
jelenleg indításkor töltődik be újra a szerkesztői ajánlatok és az adott pillanatban értelmezett cimke lista. emiatt lehet hogy egykét menet közben aktivált címke nem jelenik meg a listában, vagy nem megfelelő színnel.
plusz ilyenkor rendelődnek a felhasználóhoz az új kuponok, ezért csak következő indításkor lesznek ott.
