### ISSUE TITLE
Program címkék, amik úgy tesznek, mintha Evés címkék lennének

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#114]
A Programok címke előszűrés oldalon vannak címkék, amelyek nem jelennek meg a listában, noha van rajtuk találat (Családi, Előadás, Fesztivál)

Fura módon ezek a címkék a program adatlapján úgy tesznek, mintha Evés kategóriás címkék lennének (pirossal jelennek meg)

És van olyan címke, ami megjelenik a Program címke előszűrés oldalon, de nincs rajta találat (pl. Sport)

![pppoiu](https://cloud.githubusercontent.com/assets/16239437/13410060/1642132e-df36-11e5-8218-0c2237337243.JPG)
(címkék a "La tempesta del mio cuor" című program adatlapon)

**Comment by paneksandor** [comment]
Ez reggel mar nem jelentkezik! Csak annyi maradt belole, hogy a sport cimke uresen is megjelenik.

**Comment by duroakos** [comment]
jelenleg indításkor töltődik be újra a szerkesztői ajánlatok és az adott pillanatban értelmezett cimke lista. emiatt lehet hogy egykét menet közben aktivált címke nem jelenik meg a listában, vagy nem megfelelő színnel.
