### ISSUE TITLE
Prognózis

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#119]
Sziasztok, a héten sajnos jobban be kell osztanom az időm. Kérhetek egy nem kötelező érvényű, belső használatú prognózist, akár szóban is, hogy milyen munkák kb mikor lesznek tesztelhetők?

Pl. néhány tétel:
- Az adminos funkciók listájából sok funkció megvan, de sok hiányzik még (admin jogok, kiemelések, QR kód generálása, stb). 
- iOS jelenleg nem tesztelhető, bejön a nyitó és még a kategóriák sem kattinthatók
- Az Akciók, Push működését még nem tudtam kipróbálni
- Programok CSV-ből feltöltés

**Comment by duroakos** [comment]
az ios teszthelhető, csak ki kell löni teljesen. 
mivel az akciók számaival tesztelgettetek emiatt picit megkavarodhatott az api.

**Comment by duroakos** [comment]
Ahogy látjátok folyamatosan dolgozzuk le a hibajegyeket / új kéréseket.
Mindig azoka hibajegyek élveznek prioritást amik a tesztelést feltarthatják.

De a mai nap tuti elkészül a QR generálás és akkor tudjátok az akciókat tesztelni. 
Illetve az adminos dolgokkal is tudunk haladni.

**Comment by paneksandor** [comment]
Köszi, Ákos, azzal tudok segíteni, ha egy-egy üzenetet küldtök, amikor egy addig ki nem próbált funkció tesztelhető. Én addig maradék időben nyomogatom a többit.

**Comment by paneksandor** [comment]
Ha este lesz új verzió, akkor az megy majd az androidos gépeken? A holnap reggeli sales tréning miatt kérdezem... 

Most újratelepítettem a frappe-0226-ost a Lenovo a606-os gépemre és nem megy, ahogy addig. (Azért vettem le, mert akartam nézni, a régi verzió megy-e, hogy végső esetben azt tegyük az értékesítők telefonjára)

(Lehet, h csak az én gépemre oldottátok meg, hogy menjen és tesztelhető legyen? Mert a többi androidos gépen csak egy puszta nyitó jön be.)

Ha reggelig lesz új verzió, akkor minden ok.

**Comment by duroakos** [comment]
még jó hogy kihámoztam a mondandódból hogy új telepítéskor nem ad vissz az api adatot.
javítva.

reggelig viszont most nem ígérek App verziókat.

**Comment by paneksandor** [comment]
Köszi, így jó, most megy mindenkinél
