### ISSUE TITLE
Hogyan kerül a címke az előszűrés oldalra? (admin)

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#12]
Az adminban a címke szerkesztésnél kellene tudni megadni, hogy megjelenjen-e a címke a kategóriája előszűrés oldalán. 

Az előszűrés oldalon 6-8 címkét szeretnénk megjelentetni a kategóriából , a többi címkét pedig csak az utószűrésnél. Így a user nem bizonytalanodik el az általánosabb és a részlet címkék között.
Jelenleg minden címke kikerül az előszűrési listába.

Vigyázni fogunk arra, hogy az előszűrési címkék közül legalább egy rajta legyen minden adatlapon.
(Ez benne van ugyan az adminos listában, de a tesztelés miatt jó lenne előrevenni. )

**Comment by duroakos** [comment]
automatikusan csak azok kerülnek oda amikhez tartozik is hely/akció/program.
a sorrend pedig ugye adminból megadható.
