### ISSUE TITLE
Egy hely egyszerre csak egy QR kódos akciót tud futtatni vagy többet is párhuzamosan?

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#122]
Sejtem, hogy egyet, mert a hely oldalán van a QR megtekintése, nem az Akció oldalon.

**Comment by duroakos** [comment]
többet is. hiszen az azonosítás visszafele van. 
a QR kód csak azt hivatott szolgáltatni hogy bizonyitja hogy azon a helyen van a felhasználó.
