### ISSUE TITLE
Program neve a program adatlapról eltűnt

### ISSUE THREAD

**Issue by gerezs** [DelightSolutions/frappe-feedback#125]

**Comment by duroakos** [comment]
Ti kértétek hogy a short name jelenjen meg.
https://github.com/DelightSolutions/frappe-feedback/issues/112

**Comment by paneksandor** [comment]
Ja, ja. De a Helyeknél nem úgy van, hogy ha nincs megadva Rövid név, akkor megjelenik a Név (mivel oda mindenképp kell adat). Vagy rosszul emlékszem? Ha ez nem megy, maradjon így. De akkor majd a csv-ből program feldolgozásnál figyeljünk, hogy a program címe mindkét helyre menjen.
