### ISSUE TITLE
Hogyan legyen, ha az adminos 2-nél több kiemelést visz fel egy listába egy napra

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#127]
Attól tartok, van 2 ütköző szabályunk a lista élére kiemelés terén.

1.) Egy lista fölött csak 2 kiemelt elem lehet 
2.) Egy listában az a hely lehet kiemelt, amelyik kiemelés nélkül is benne lenne a listában (rajta van a címke) - vagyis, a Fagyizó lista fölé ne kerüljön étterem.

De mi legyen akkor, ha egy Helyen több címke is van, és ezért az egyik címkén ez a hely lesz a harmadik kiemelt a lista élén. 
Vagy, ha az adminisztrátor tévedésből 3-at állít be egy listába?

Javaslom, (főleg utóbbi esetre) hogy ilyenkor az adminisztrátor kapjon üzenetet, de továbbléphessen és hagyjuk megjelenni a felvett 3. kiemelést is. Így a partnerek felé könnyebb kezelni az adminos esetleges tévedését.

Ti hogyan terveztétek? (Biztosan jobban)

**Comment by duroakos** [comment]
engedi a rendszer a többet. Ha igény van rá akkor lehet többet is. (Ti belső döntésetek később is)
bannert kategóriához lehet rendelni így kategóriánként kell gondolkodni. Vagyis ha 2 kiemelés van evés kategóriában. javasolt az összes releváns cimkét beállítani, hogy azon listák tetején is legyenek.

elkészült egy kiemelések menüpont ahol adott napra lehet látni egyszerre az összes értékesíthető elemet. így elkerülhető, hogy keresztbe promózás legyen. remélem ez hasznos lesz.
