### ISSUE TITLE
Címke nélküli Helyek az utcai programok fogadására

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#128]
Lesznek helyek, amikre nem adunk címkét (csak egy kategóriát), mert ezek a helyek az utcai programok vagy a nem szórakozóhelyen rendezett programok fogadására szolgálnak. Ezek csak a Program oldalán vagy a szabad szavas keresésben megtalálhatók.
Pl.  ilyen hely:	"Címke nélkül létrehozott hely utcai programnak"

Ezzel kapcsolatos:
- Ha egy Hely adatlapon a "Teljes nyitva tartás" mezőkben nincs megadva semmi, akkor ez a funkció ne jelenjék meg. De legalább üresen maradjon a napok melletti adat; most a Zárva szöveg jelenik meg.
- Ugyanígy kellene "A hely címkéi" esetében, ha lehet. 
- Segítség lenne, ha ezeket a címkétlen helyeket az adminban csak külön lehetne listázni

**Comment by duroakos** [comment]
Ahol nincs cimke az adatlapon ott a hely cimkéi felirat ne jelenlen meg.
Ahol az összes nyitvatartási adat üres ott pedig a teljes nyitvatartás rész tűnjön el.

**Comment by paneksandor** [comment]
Így tökéletes, köszi.

Sajnos  a Közelben listában akkor is megjelennek ezek a helyek, ha nincs rajtuk címke.
Van ötletetek, hogyan lehetne kiküszöbölni? Egy flag a hely adminjában "Csak programhely" ?
