### ISSUE TITLE
A hely adatlap adminban mi célja van a QR szöveges mezőnek?

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#133]
Ennek:

![xccx](https://cloud.githubusercontent.com/assets/16239437/13477244/d1ea8084-e0cb-11e5-9105-fda88c3f0015.JPG)

**Comment by duroakos** [comment]
levélben leírtam, de itt is legyen meg.

A helynél a QR kód azért van adminban hogy ott megadhat teszőleges szöveges tartalmat (pl a hely QR kódja lehet a hely weboldala is) és mivel a helyhez van az Akció rendelve. így az összes QR-es akció arra helyre használhatja ezt a QR-t és mivel a QR kód leolvasást a szerveroldalon hitelesítjük ezért ha egy kupon akció közepén cserélni szeretnék a QR kódot, semmi akadálya.
