### ISSUE TITLE
Kupon beváltása gomb több beváltható kupon esetén

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#138]
Egy user többet is beválthat ugyanabból a kuponból. 
Kattint a "kupon beváltás" gombra, jön az ablak, jóváhagyja.
Ha még van lehetősége, visszakapja ugyanazt a gombot, és ez zavarba hozza, hogy sikerült-e a művelet, illetve nem tudja, mennyi lehetősége van még.

Lehet-e így:
A jóváhagyás ablakban kapjon üzenetet, hogy "Sikeres beváltás, maradt 2 kuponod!"
Vagy a gombon legyen "5 kupon beváltása"  és a beváltás után "4 kupon beváltása"
Vagy a gombon "kupon beváltása 5/0"  majd "kupon beváltása 5/1"

Az alapszöveg jobb lenne így: "kupon beváltása", mivel a kuponbeváltás egy szó lenne.

A QR és a kuponbeváltás Androidon működik, köszi!

**Comment by duroakos** [comment]
Kitalálunk valami izléseset.

**Comment by paneksandor** [comment]
Bocs, iOS-en ez jól megy
