### ISSUE TITLE
Adatlap éjfélig nyitva tartó helyek (24:00) (Admin)

### ISSUE THREAD

**Issue by gerezs** [DelightSolutions/frappe-feedback#14]
Nem veszi be, ha egy hely 24:00-ig van nyitva. Ha az a logika szerint megyünk, hogy az éjfélig nyitva 23:59 akkor is kijelzésnél 24:00-kell, mert azt értik az emberek a másik (23:59) meg fura.

**Comment by duroakos** [comment]
Nem is lenen jó ha bevenné, hiszen már van validáció azon a mezőn (talán az admin megtekintésekor volt kérés hogy ne szöveges mező legyen hanem egy időbeviteli).

Abból az okból hogy az informatika és úgy általában az órák sem ismernek olyat hogy 24. óra.
Így erre az időpontra a 0:00-t javasoljuk használni. 
Az emberek pedig tudják hogy az bezony éjfélt jelent.
