### ISSUE TITLE
Evés-Ivás listanézetben távolság kijelzése 2 tizedes jeggyel

### ISSUE THREAD

**Issue by gerezs** [DelightSolutions/frappe-feedback#141]
1 km felett a távolság két tizedesjegyig legyen kijelezve (mint Adroidnál). 1 km alatt pedig m-ben

**Comment by tthbalazs** [comment]
5 karakter felett már nem fér ki a távolság, androidon is 1-100 között van csak tizedesjegy. De akkor iOS-en is lesz. (1-100 között)

**Comment by gerezs** [comment]
Sztem 1-2 px-lel kisebb lehet a listában a képek alatti felirat (szöveg) -> Androidnál kisebb és nem zavaró

**Comment by tthbalazs** [comment]
Mekkora eszközön nézed? Mert nem mindegy.

**Comment by gerezs** [comment]
iPhone 5
