### ISSUE TITLE
Programoknál a kezdő dátum 1 órával, a vége dátum 2 órával siet

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#153]
A Listakép alatt és az adatlapon is

**Comment by paneksandor** [comment]
A dátumnál légyszi használjuk a 12. 08. írásmódot (szóközzel és ponttal a végén). Ha nem fér ki, a szóközt hagyjuk el, a pontot ne....

**Comment by tthbalazs** [comment]
A dátum nem siet, a szerveren mindent UTC időzónában tárolunk, és ebből számolódik mindig a felhasználó időzónájába a kezdeti és vége dátum. (Ami jelen esetben GMT + 1).

Ahol +2 órát látsz, ott már nyári időszámítás van (GMT +2)
