### ISSUE TITLE
Kiemelés admin

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#162]
Szia Ákos, átnéztem a Kiemelés admint. A logikája tök jó, és hasznos lesz.

Alább leírtam 3 problémát, amin  nagyot segítenél. Ez lenne legjobban szem előtt a salesnek.

Az első kell a megfelelő használathoz, a második egy nagyon időpazarló és munkanehezítő problémát oldana meg, a harmadik könnyű, de nagyon hasznos akkor, amikor nem egy napot, hanem egy periódust tekintenénk át az adminban.

Holnap 11-kor ott vagyok nálatok support ügyben, ha szóban beszéljünk, keress...

**1.) Kategória szerinti bontás, címkék kiírása oszlopban**

A „Kiemelt helyek” admin jelenlegi állapotában az adminos azt látja, hogy arra a napra hány kiemelt hely van. De nem tudja, hogy egy kategórián belül mennyi kiemelt lesz, és a címkékről sincs támpontja.

Ezt javaslom:
-	A „Kiemelt helyek” alatt kategóriánként (Evés, Ivás és Élmény) legyenek kilistázva a helyek. Vagyis 3 kis lista legyen a 3 kategória helyeivel. Ha egy hely több kategóriába tartozik, akkor az mindegyiknél legyen ott.
-	A találati listában külön oszlopban soroljuk fel a hely aktív címkéit, kategória szerint csoportosítva (hogy az adminak legyen ennyi támpontja: egy címke listájában nem lesz e 2-nél több kiemelés). 

A kiemelt Programok kezelésénél a programok mellé írjuk ki a Program-címkéket egy oszlopban.

A Bannereknél a Target oszlopba a célzási kategória nevét írjuk ki.

**2.) Több periódus rögzítése a hely adatlapján**
Ha idén egy nagyot akarsz segíteni, akkor itt van:
Számos helyünk lesz, akik a hétnek csak bizonyos napjaira akarnak kiemelést venni. 
Jelenleg a Hely adminban egyszerre csak egy időpont (periódus) adható meg a kiemeléshez. 
Ez oda vezet, hogy az adminosoknak hétről hétre újra végig kell járniuk a helyeket, hogy rögzítsék a kiemeléseket, amit pedig előre tudnak, és egyszerre is lehetne rögzíteni. Nagyon időpazarló, ha mindig vissza kell térni.
Mivel ezek a „minden szombaton” típusú kiemelések nem rögzíthetők előre (csak hétről hétre), nem is lehet látni őket a „Kiemelés adminban”, ezért egy másik ügyfél elfoglalhatja előlük a kiemelést.  

Ehhez kellene, hogy az Hely adatlapján több periódust is rögzíthessünk. 

Így gondolom:
-	A mostani módon felveszünk egy periódust, jóváhagyjuk, az kiíródik, eltárolódik (de lehet törölni).
-	A mostani módon felvesszük a következőt stb. A felvett periódusok pedig ott listázódnak a Hely adatlapján és figyelemebe vehetők a „Kiemelés adminban” 

**3.) Periódusra áttekintés**
Egy egyszerű áttekintő táblát tudnátok készíteni, ami egy periódus napjaira mutatja a kiemelt helyek számát (csak egy számot). 

Így gondolom:
- Megadok egy periódust
- Jóváhagyásra kapok egy egyszerű táblát, benne Evés, Ivás, Élmény, Program kategóriára naponta egy-egy szám: az illető kategóriában aznap hány hely van kiemelve.

**Comment by paneksandor** [comment]
Ok, a 2.pont alatti "tobb periodus rogzitese" a kiemeleseknél plusz hirdeteskezelesi igény...

De, ugyanez a programoknál ? Egy szinhazi darabnak vagy egy  szombatonként rendezett sztriptíznek annyi adatlapja lesz, ahany eloadasa? akár naponta 2-3? Ha meg perioduskent tesszem fel, egy adatlapra az osszes eloadast, akkor ez a lista èlén ragad, mert a listát a program idopontja szerint képezzuk.... 

Erre a program idopont problemara nincs valami jobb megoldasod ?

**Comment by duroakos** [comment]
Programok:
A naponta több programot erős túlzásnak érzem. De Igy megoldható
A hetenként ismétlődő program : módosítható a kezdő és vége dátum. és amikor lejár automatikusan inaktív lesz. A következő alkalom beállítása után ujra aktivá tehető és nem kell mindig felvinni.

Amit pedig személyensen beszéltünk hogy kategóriák címkék bekerülnek a kiemelések oldalra, megtörtént.
