### ISSUE TITLE
Szerkesztő ajánlja háttérkép betöltődése

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#164]
Android Lenovo a606-on a harmadik vagy valamelyik további Szerkesztő ajánlja (SzA) oldalon vagyok. 
Itt kattintok valamelyik linkre a nyitón. 
Visszalépek a bal felső vissza gombbal.

Ekkor nem arra a harmadik SzA oldalra kerülök vissza, ahonnan elindultam, hanem az első SzA oldalra, és ennek nem töltődik be a háttérképe (sárga van mögötte). 
Ha innen előre, majd vissza léptetek, akkor betöltődik.
Ha a második SzA oldalról kezdem, elkattintok, majd visszatérek, akkor is az elsőre visz vissza, de ekkor betöltődik a háttérkép.

iOS-en a vissza gomb után visszakerülök a 3. SzA oldalra

Android Lenovo a606-on a SzA oldalakat gyorsan léptetem: egy-egy másodpercre a sárga oldalt kapom, később töltődnek be a háttérképek. (Ugye, nem kell minden megjelenítésnél letölteni ezeket a képeket, mert cachelve vannak az oldalak? 
Ugyanez iOS-ben nem fordul elő, akármilyen gyorsan léptetek.

**Comment by paneksandor** [comment]
Szia Ákos, rendes wifi mellett is ugyanaz a jelenség van. Ès a korábbi Android verziokban ez nem jelentkezett, vagyis korabban a visszalepesnel megjegyezte, hogy melyik SzA oldalrol indultam, es foleg betöltődött minden SzA fotó...

**Comment by gerezs** [comment]
Itt jól látszik miről van szó: http://media.delmagyar.hu/ftp/wd/szerkeszto-ajanlja-sarga-hatter.mp4
