### ISSUE TITLE
A user nehezen jött rá, hogy a Szerkesztő ajánlja léptethető

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#165]
Elég sok user bénázott ezzel a funkcióval.
A léptetés bulletjeit nem vették észre. A golyóknak kellene egy éles fehér kontúr! 

Sokan a sárga nyíllal akartak léptetni, de azokat hagyjuk, majd megtanulják.

**Comment by duroakos** [comment]
ezek a pöttyök egyértelmű gyári kontrollok. 
esetleg más színűvé lehet varázsolni a pöttyöket ha ez tényleg ekkora igény (csak kontúrt nem).

**Comment by tthbalazs** [comment]
Ide még várjuk, hogy mi legyen a pöttyökkel.

**Comment by paneksandor** [comment]
Maradjon így, köszi, a más szín nem lenne szép.
