### ISSUE TITLE
Hogyan kell hivatkozni az Akció listára?

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#169]
Pl. a Szerkesztő ajánlata, a Push vagy a Banner esetében, ha azt akarjuk, hogy az Akció listára mutasson?

És a Közelben térképes oldalnak mi az elérése?

**Comment by duroakos** [comment]
frappe://list/Akció
és
frappe://list/Közelben (ez a térképet fogja megnyitni)

ez iOS-en az esti verzióban már így fog működni. de andriodon már most is. 
A 2frappés szerk ajánlatot ilyenre lőttem be.
