### ISSUE TITLE
Az előszűrés oldalon megjelenő címkék száma a listából

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#176]
A #12 ben van egy félreértés. Kezdettől fogva azt kértük, hogy a Kategóriák előszűrés oldalán ne minden címke jelenjék meg, hanem egy bizonyos számú. Az első X számú a listából, és az X értékét mi adhatjuk meg. (Ezek általános címkék lesznek, és egy közülük minden adatlapon rajta lesz.)

Ezt nem most találom ki, hanem a Gáborral, még a design véglegesítésekor megegyezett megoldást írom. Az értékesítőknél már ott vannak ezek a kategóriánként kijelölt címkék...

Idézek a 2015.11.12.-én küldött  "Grafikai szakasz lezárás, teljesíts" mailetekből:
"Lényegében egy sorrend lesz, az egyik nézeten ennek csak X eleme látható majd, a másodikon pedig mindegyik. A Második nézeten egy „Többet szeretnék” felirat segíti az értelmezést, hogy szűrésről van szó."

Szóval, szeretnénk megadni kategóriánként (evés, ivás, élmény) azt a számot, amennyi címke a sorrendbe állított listából **az előszűrés nézeten** megjelenik.

--------------

A hely adatlapján a címkék listája nagyon lelóg, sok helyet foglal, illetve keverednek benne a kategóriák. Lehetne kategória szerint 3 oszlopban, vagy még inkább **3 többválasztós lenyílóban** listázni?

------------------
Az újonnan elkészített Kiemelés admin címkét légyszi, legalább kategória szerint különítsd el a pl. 3 sorban, de legjobb lenne sorrend szerint is.

**Comment by duroakos** [comment]
a paraméterek (leánykori nevén statikus szövegek) menüpontba kivezetésre kerültek a limitek.
Ezek a számok határozzák meg hogy a teljes címkelistá első hány elme jelenjen meg az előszűrés oldalon.

**Comment by paneksandor** [comment]
Remek, köszi szépen!

**Comment by paneksandor** [comment]
Ennek az issue-nak a 2. és 3. részét ne felejtsétek légyszi. (főleg a 2.-at)
