### ISSUE TITLE
Üres címkék megjelenése az appban

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#177]
Az appban ne jelenjenek meg az "üres" címkék (előszűrés, utószűrés listában), vagyis azok, amelyeken nincsenek egyetlen helyen sem rajta. Jelenlegi példa: Kifőzde, Hamburger, Elvitel, pékség (evés) - ami üresen megjelenik.

**Comment by duroakos** [comment]
csak megjegyzem hogy ez egy igencsak combos lekérdezés árán valósult meg.
