### ISSUE TITLE
Hogyan választunk első számú galériaképet?

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#178]
A #3 issue ezt nem érintette. Ha több kép van a galériában, hogyan választjuk ki azt, amelyik az adatlap kép helyén ezek közül megjelenik?

Pl. Jazz Kocsma nevű helyen.

Bocs, ha más issue is érintette.

**Comment by duroakos** [comment]
Mindig az elso az.

**Comment by paneksandor** [comment]
Jön a partner, és azt kéri, hogy a galériából egy másik kép legyen az adatlapon. Így nem tudjuk oda tenni...

**Comment by duroakos** [comment]
most már lehet elsőnek jelülni képet helynél programnál és akciónál is.
