### ISSUE TITLE
Az Akció listaképekről lelóg a felirat

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#179]
iPhone 5-ös (Zsolt-féle), ahol 3 soros lett az akció címe, ott lelóg a felirat.

Az kuponok kezelése első tesztre működik, köszi!
A beváltási gomb szuper lett.

**Comment by tthbalazs** [comment]
Limitáltam a sorok számát. Négy sorba kéne maximum beleférnie, hogy olvasható is legyen.
