### ISSUE TITLE
A távolság szerinti rendezés nem jó a listákban

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#181]
Ivás > Bár címke listájában látszik: Távolság szerint nincs jól rendezve a lista

**Comment by tthbalazs** [comment]
Erről kérnék egy screenshotot, mert nálam minden stimmel.
Nem lehet, hogy a kiemelés miatt tűnik így?

**Comment by gerezs** [comment]
Ez a másik ticket ezt a hibát írta le: https://github.com/DelightSolutions/frappe-feedback/issues/142
![tavolsag-anomalia](https://cloud.githubusercontent.com/assets/8058830/13605438/e2fba698-e547-11e5-8017-e654b8d31922.png)

**Comment by tthbalazs** [comment]
Ez egy adminos hiba volt, ilyen már nem kéne hogy legyen az alkalmazásban.

**Comment by gerezs** [comment]
De ha itt látod és most készült a screenshot akkor van ez a hiba.
Megnéztétek a leírást, h hogy jön elő ez a hiba?

**Comment by tthbalazs** [comment]
Nálam a crashlytics még azt mutatja, hogy nem a legújabb verzióval nézed az appot. Megtennéd, hogy azon is megnézed?

**Comment by gerezs** [comment]
Oké, akkor töröltem és újra telepítettem a 0307-est.
Most fel is vettem a dolgot: http://media.delmagyar.hu/ftp/wd/tavolsag-szerint.mp4

**Comment by tthbalazs** [comment]
Nagyon jó, de ez nem az a hiba.

**Comment by tthbalazs** [comment]
https://github.com/DelightSolutions/frappe-feedback/issues/145
