### ISSUE TITLE
Adatlapon oldalról, akcióban alul-felül lapított a kép

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#189]
A hely adatlapon a kép oldalról van összenyomva, míg az Akció és a Program adatlapon lapítva van. iPhone 5

A hely adatlapon itt nézd, arc van a képen:
Ivás > Bár > Lapított kép kocsmája

Az Androidon készült megoldás szuper, vagyis az, hogy egy metszetet vesz ki a képből.

**Comment by tthbalazs** [comment]
Itt az adminos képfeltöltést módosítottuk, iOS oldalon már az optimális beállítás szerepel minden kép esetében.

A helyzet nem 100%-ig ugyan az mint androidon, ezért ne is hasonlítsuk őket össze.

**Comment by gerezs** [comment]
Lecsekkoltam egy olyan képpel amire négyzeteket tettem és a csatolmányon látszik, hogy a mai verzióban iPhone 5-ben mennyire/hogyan nyomja össze.
![adatlap-kep-torzulasimage](https://cloud.githubusercontent.com/assets/8058830/13640983/224f32ea-e617-11e5-91dc-46364430da19.png)
