### ISSUE TITLE
A Kiosztott kuponok száma 

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#190]
Ez ugye nem egyenlő az elhasznált (igénybe vett) kuponok számával?
Az igénybe vett kuponok számáról egy adatot betennél a hely adminba?
**De ez ráér**

**Comment by duroakos** [comment]
ez nem ennyire triviális.
Lehet egy kupont többször beváltani, akkor mire vagytok kiváncsiak, arra hogy melyik kupont használták fel a maximális alkalommal, vagy arra hogy melyik kupont pontosan hány alkalommal használtak fel.
Mert ezek mindegyike eléggé adatbázisterhelő. 
Szóval lassíthatja a hely adatlap szerkesztéseket.
mert ez a helyenként található kuponok száma * felhasználók száma nagyságrendű lekérdezés.

**Comment by paneksandor** [comment]
Igazából a konverzióra lennénk kíváncsiak, vagyis arra, hogy melyik kupont pontosan hány alkalommal használtak fel...

**Comment by duroakos** [comment]
mostantól a kuponoknál van enniyszer váltották be mező.
(ez mostantól él visszamenőleges beváltásokat nem tart számon)
