### ISSUE TITLE
A lejárt és archiválódott akciók, programok, bannerek, szerk ajánlatok elérése

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#192]
Ez az utolsó funkció, amit felírok.

A kiküldött push üzenetek listázása az appban, sajnos már külön fejlesztési téma lesz :)

**Comment by duroakos** [comment]
Jelenleg az tekinthető achiváltnak amit automatikusan inaktívra állít a renszer a lejárta alapján, ezek attől még listázódnak, pont hogy akár ujra lehessen őket aktiválni.

Itt mire gondolsz? van amit nem érsz el?

**Comment by paneksandor** [comment]
Ja, hogy maradnak "végleg" a listában? Én azt vártam, eltűnnek onnan... 

Ez egy idő után nagyon hosszú inaktív elemet eredményez majd, főleg a Programok esetében. A legjobb az lenne, ha a lejártak egy külön helyen lennének elérhetők, úgy ahogyan a Címkétlen helyek, és nem lennének benne a listában, .

Szóval,  lenne egy Lejártak lista.

**Comment by paneksandor** [comment]
Ide még annyi kommentet, hogy nem szeretnénk, ha a listában összekeverednének az értékesítői joggal rendelkező személy által inaktívan létrehozott és aktiválásra váró elemek azokkal, amelyek inaktívvá váltak a lejárat után. Ez utóbbiakat kellene egy külön helyről elővenni tudni.
