### ISSUE TITLE
A cím alapján generált Lat/Long koordináták Lezárható

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#193]
**update**: a Google Maps is így adja meg a címet, vagyis, rajtatok kívül eső probléma, lezárható

Beállítottam az Evés > Bisztró > Utolsó fügelevél   hely adatlapján a Szeged, Szabadkai u. 20. számot, vagyis azt, ahol éppen vagyok, a Lapcomnál.

Mentés után a Lat-Long koordinátákat átállította az adatlap.

Azonban a két egybeeső hely, a saját pozíció és a Hely pozíciója között kb 500 méter eltérés van. 
A saját pozíció helye a pontos.
Androidon és iOS-en ugyanez a helyzet.

A Közelben térképen így látszik:
![screenshot_2016-03-08-11-23-58](https://cloud.githubusercontent.com/assets/16239437/13598854/64e2b9d0-e520-11e5-93f6-dce2e8f54bef.png)

A hely térképén pedig így:
![screenshot_2016-03-08-11-16-35](https://cloud.githubusercontent.com/assets/16239437/13598723/b82cd9a0-e51f-11e5-9b06-231c00c7cee2.png)

**Comment by duroakos** [comment]
mi is a google geocoder API-t használjuk.
és az iylen esetek miatt lett úgy beállítva, hogy csak a cím változtatásakor geokódol ujra, vagyis kézzel lehet a lat-lng-t pontosítani.

lezártam.
