### ISSUE TITLE
Adatlap adminon hely/program belső app linkje

### ISSUE THREAD

**Issue by gerezs** [DelightSolutions/frappe-feedback#194]
szükség lenen arra, hogy tudjuk mi egy adatlap belső app linkje a szerkesztő ajánlja stb. helyekhez.

**Comment by duroakos** [comment]
most már ott van, viszont csak az első mentés után generálódik (a névből), nem módosítható mezőként lesz látható. másolni lehet belőle, módosítani nem.

**Comment by gerezs** [comment]
Itt az lenne kellene, h ki lehessen könnyen jelölni és másolni (nem kell, h input mező legyen) és ha az a link lenne amit bemásolhatunk a másik helyre (ha a bannereknél, szerkesztő ajánlja résznél szükséges a frappe//.. előtag, akkor az is legyen ennek a linknek a része.)
