### ISSUE TITLE
Push üzenetek időzítése

### ISSUE THREAD

**Issue by gerezs** [DelightSolutions/frappe-feedback#195]
Most (12:400 és 12:50 között) kaptam egy pusht amit megnéztem adminban és ott azt láttam, hogy 12:11 -re volt beállítva? 
Miért van ez a / ennyi késés?

**Comment by duroakos** [comment]
mert az most csak beledobtam kézzel. a kiküldés dátum pedig korábbra volt állítva, hogy konzolból azonnal kiküldhessem, és ne kelljen megvárnom az óránkénti automatikus kiküldést.

**Comment by gerezs** [comment]
Tehát óránként fog lefutni egy cron ami kiküldi?

**Comment by paneksandor** [comment]
A Push üzenet mellett ez a kép jelenik meg... A Frappé logónkat vagy az ikonunkat oda tudnád tenni?

![screenshot_2016-03-08-14-25-02](https://cloud.githubusercontent.com/assets/16239437/13603037/ad28e9fc-e53a-11e5-84bb-4308bbb5fd16.png)
