### ISSUE TITLE
Élmény listánál nyitva/zárva tartás rossz jelzése

### ISSUE THREAD

**Issue by gerezs** [DelightSolutions/frappe-feedback#196]
Itt az idő szerint zárva tartó helyek ugyanúgy zölddel vannak jelölve, mint a valóban nyitva lévő helyek.

**Comment by tthbalazs** [comment]
UE: https://github.com/DelightSolutions/frappe-feedback/issues/182

**Comment by tthbalazs** [comment]
Javítottam minden nyitvatartással kapcsolatos hibát.

Nyitvatartásnál fontos, hogy csak akkor működik megfelelően ha:
- Nyitás és zárás is van megadva egy naphoz
- Nincs se nyitás se zárás megadva egy naphoz

Ha csak nyitás vagy csak zárás van megadva, azzal nem tudok mit kezdeni
