### ISSUE TITLE
Bannerkép feltöltéskor átméreteződik?

### ISSUE THREAD

**Issue by gerezs** [DelightSolutions/frappe-feedback#198]
Ha nem, akkor légyszi írjátok ki a méretet amit fel kell tölteni hozzá!

**Comment by duroakos** [comment]
A pontos képméretek és arányokat korábban elküldtük levélben, ha ezek mentén készül a tartalom akkor munden csudiszép lesz.

Átméretez lefele is természetesen, hiszen egy kis androidos krumplira fölösleges óriási kép.
Jelenleg mindenhol vág a rendszer, ha nem stimmel az arány, de nincs ráhatásunk arra hogy hol vág, úgyhogy célszerű tartani az arányokat.


a legnagyobb kijező méretek határozták meg az alábbi számokat (android - xxxhdpi)
amennyiben ezen méretekben kerülnek fel a képek akkor a szerver automatikusan a többi kisebb méretre is elkészíti őket.
ha ezektől kisebb vagy más arányú képek kerülnek feltöltésre akkor az alkalmazás minősége erősen romolhat, mivel a kinézet erősen függ a képektől.
Illetve egyes kijelzők aránya miatta képek szélei levágodhatnak, így a fontos részletek középen legyenek lehetőség szerint.

szerkesztői ajánlat: 1440 * 1920px
listába kép:		1312 * 392px
adatlap galéria:	1440 * 2560px (jelenleg az első galéria kép lesz az elhomályosított adatlap háttér)
lista alján banner: 	1440 * 200px

**Comment by gerezs** [comment]
Értem, köszi, itt csak akkor az lenne hasznos ha a Képe felirattal a betöltődés előtt így lenne: Kép (1440 * 200px) és akkor az adminból fogjuk tudni a minimális méretet.
Kösz!
