### ISSUE TITLE
Hely adminnál vmi szétnyomja a felületet

### ISSUE THREAD

**Issue by gerezs** [DelightSolutions/frappe-feedback#199]
Itt is vmi szétnyomja az oldalt
http://frappe.delso.org/places/new-york-etel-es-salatabar/edit

**Comment by duroakos** [comment]
melyik irányba? vagy hol? dobj kérlek egy screenshotot.

**Comment by paneksandor** [comment]
Szerintem a Szerkesztő ajánlja helyen a "megtekintés" nézetnél látta ezt:
![fffhhh](https://cloud.githubusercontent.com/assets/16239437/13630733/25cf7c58-e5e1-11e5-9a17-9d98d35d9810.JPG)

**Comment by gerezs** [comment]
![frappe_admin_-_2016-03-09_10 53 17](https://cloud.githubusercontent.com/assets/8058830/13631474/26ef63d8-e5e5-11e5-82dc-d9b5055fdc75.png)

**Comment by duroakos** [comment]
igazítottam rajta, meg azon is amit sanyi mutatott

**Comment by gerezs** [comment]
Szerintem pont az enyémet nem sikerült javítani.
Itt még mindig vmelyik input mező szétnyomja. Ha inspectorban nézem és a képfeltöltés mezőknél törlök ki elemeket akkor ez megszűnik -ott lesz vmi. 

![delso-bootstrap-cucc](https://cloud.githubusercontent.com/assets/8058830/13634336/3352e086-e5f5-11e5-9af9-1fd8414a15d9.jpg)

**Comment by gerezs** [comment]
Illetve észrevettem - tudom nem rám tartozik - h ennél az oldalnál nem töltődik be places.css és places.js Lehet épp abban csinálod a javítást és ezért nem látszik.

**Comment by duroakos** [comment]
ezek a js és css hiányok minden controlleren fenállnak ha jobban utána nézel. amig napi szinten 100szor kell feltölteni új verziót addig nem állítom be az asset-kezelést élesre mert 5ször addig tartan a egy deploy.

nem abban készült a változtatás.

Segíts kérlek hogy inspect helyet inkább egy böngésző nevet és verziót nyomsz.

**Comment by gerezs** [comment]
Á, ez Chromeban jól jelenik meg, értem miért nem találtad meg.
Win8 FF 44.0.2 -ben készült a screenshot.
