### ISSUE TITLE
Az iOS-es kijelzőn a logón nincs rajta a Frappé felirat + 1 kérdés

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#200]
A Google Play és App Store listájában kötelezően ugyanaz a logó jelenik meg, mint a kijelzőn?

A kijelzőn nem fért be jól az app tetején lévő (remekül eltalált) Frappé felirat, ezért nem ez lett a logó.
De a Playben ez kifejezőbb lenne.

Ezt azért kérdem, mert a Lapcom marketingtől a terméknév megjelenésével kapcsolatos kérdést kaptam, és persze azt szeretnék, hogy a Frappé felirat legyen minél több helyen.

(Tudom, hogy már elfogadtuk a logót....)

**Comment by paneksandor** [comment]
Update! Tárgytalan lett a kérdés! Az elfogadott logó jelenjék meg következetesen mindkét helyen (kijelző és Google Play)! (De iOS-en a felirat szükséges)

**Comment by tthbalazs** [comment]
Ez így akkor megfelel?

![simulator screen shot 09 mar 2016 14 14 58](https://cloud.githubusercontent.com/assets/871355/13636258/52379ae4-e601-11e5-87b3-96880e6309cc.png)

**Comment by paneksandor** [comment]
igen, köszi
