### ISSUE TITLE
A listaképek alatti sor betűi eltérő méretűek

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#207]
Pl Az Étterem listaban gyakran a km kisebb, míg a Programok listaban a Csaladi > "Szechenyi teri program" elemnel latszik, hogy amikor a vége dátum nem jelenik meg, aranytalanul nagy a datum betuje a km betujehez kepest. 

Sejtem, hogy a sok kijelzo es felbontas miatt van. De ha egysegesen a legkisebb szukseges betut hasznalnank, akkor nem lenne jobb? 

Ha eleve nem jo kerdes, akkor csak jelezd, nem kell screenkép.

**Comment by tthbalazs** [comment]
Ez mindig így volt, a betűméret adaptálódik a rendelkezésre álló helyhez képest (amennyire tud), hogy 
1. ne legyen ... a szöveg végén
2. ne legyen nagy üresség az ikonok között, és rendezettebbnek tűnjön

Ha gondoljátok kicserélem egy olyan pici betűméretre ami mindenhol jó, és akkor nem adaptálunk.

**Comment by paneksandor** [comment]
Köszi, Balázs, légyszi cseréld le, legyen egyforma minden betű.
