### ISSUE TITLE
iTunes Connect app sku

### ISSUE THREAD

**Issue by gerezs** [DelightSolutions/frappe-feedback#208]
Ezt csak azért küldöm, mert talán fontos tudnotok milyen SKU-val regisztráltam be az appot.
Illetve ha írsz egy e-mailtcíme , akkor hozzáadlak fejlesztőként.

![frappe-itunes connect](https://cloud.githubusercontent.com/assets/8058830/13662469/fb90a6f0-e69a-11e5-8dee-66cae67d3ca3.png)

**Comment by tthbalazs** [comment]
Ez majd csak a feltöltés előtt lesz fontos, teszt alatt nem cserélném le mert akkor mindent újra kell generálni, illetve az eszközöket is újra kell regisztrálni

**Comment by gerezs** [comment]
Oké, akkor majd szóltok.
