### ISSUE TITLE
Offline állapotban mit látok az első használat után?

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#21]
Jelenleg, ha offline vagyok nem érem el azt a tartalmat sem, amit már korábban megnéztem.

Arra mindenképpen fel kell készülnünk, hogy offline is lehessen valamit használni, gondolva arra, hogy sokan wifin használják, és ha offline kerülnek, így most nem találnak semmit.
Attól pedig, hogy mindig újra letöltessük az adatbázist, azok fognak szentségelni, akiknél számít a letöltési korlát.

Szóval, ezt kérjük:
- Első használatkor töltődjék le a nyitó a képeivel, a szerkesztő ajánlja, a listák listaképekkel és az adatlapok (esetleg az 1 főkép nélkül). Ezt az első használat után láthassa a user offline is. 
- A következő használatkor pedig az, ami azóta frissült.
Így a user offline tudja valamennyire használni az appot, csak persze nem kapja, ami azóta frissült

A csak online használható app egy vidéki városban eléggé korlátozott lenne.

**Comment by duroakos** [comment]
Pedig ahogy a korábbi találkozókon is kihangsúlyoztuk, az alkalmazás online működik.

Minden szerveroldalon került implementálásra (rendezések, lapozás, felhasználóhoz rendelt adatok kezelése (kuponok, kedvencek, stb)). Pl a kupon kezelés offline teljesen már logikát igényelne a visszaélések visszaszorítása miatt.

Semmiféle helyi adattárolást nem terveztünk pontosan emiatt az alkalmazásokba.
És ez nem is olyan funkcionalitás amit az alkalmazások jelen állapotában könnyen bele lehetne fejleszteni.

A 3G/LTE lefedettség szerintem pedig egy vidéki városban sem lehet kifogás 2016-ban, amikor még a mátrában az erdő közepén is lehet videót streamelni.

**Comment by paneksandor** [comment]
Szia Ákos, ez nem kifogás, hanem a helyi valóság.  
Ez azt jelentené, hogy az 1 gigás csomagú a felhasználó,  egy idő után kerülni fogja a használatot, mert mindig újra fogyaszt. A wifis egyetemista pedig nem tud vele mit kezdeni az utcán, ahová az appot szántuk. Erre én nem mondtam igent, meg sem fordult a fejemben, hogy az online működés mellett az sem fog látszani, amit előzőleg letöltöttem és eltárolódott.

Szóval erre szeretném, ha megoldást találnánk.

**Comment by paneksandor** [comment]
Abból indulok ki, hogy a GPS-t offline is tudja használni. Ha plusz fejlesztést jelent az, hogy offline használattal lehessen valamit kezdeni, írd meg légyszi. Szóval, nézzük meg, mit lehet tenni.

**Comment by duroakos** [comment]
Ezt Ferivel lebeszéltétek. Az app jelenleg cska online megy. Lezárom.
