### ISSUE TITLE
Adatlap adminon hely/program belső app linkje #2

### ISSUE THREAD

**Issue by gerezs** [DelightSolutions/frappe-feedback#215]
Itt 2 dolgot szeretnénk ha módosítanátok:
1. az az útvonal legyen itt amit máshova bemásolva elfogad a rendszer. Ha kell elé frappe/... előtag, akkor az legyen ott.
2. Nálam FFban egyszer engedi kijelölni, de másolni már nem engedi. Ezután kijelölni sem engedi.
Itt megtaláltam az idevaló FF bug reportját, ahol azt írja disabled helyett readonlyt javasol: https://bugzilla.mozilla.org/show_bug.cgi?id=253870

**Comment by tthbalazs** [comment]
Ez nekem inkább firefox bugnak tűnik mint admin bugnak, de utánajárunk.
