### ISSUE TITLE
Ha még belenyúltok: egy sortávolság hiba a Szerkesztő ajánlja oldalon

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#218]
Az első sorköz nagyobb, mint a második. A masodik sorkoz magassaga eleg.
![screenshot_2016-03-11-08-39-48](https://cloud.githubusercontent.com/assets/16239437/13696341/0d34165a-e766-11e5-8366-e148b286ad6a.png)

**Comment by duroakos** [comment]
ezt automatikusan kezeli a rendszer ebbe nincs beleszolásunk sajnos. Ez egy textbox, nem egy word doksi, hogy soronként adjak meg sortávot. Valószínűleg a betűtipus és szavakat alkotó betűk együttese adja ezt az optikailag valóban nem egyenlőnek tűnő eloszlását a soroknak.
