### ISSUE TITLE
Admin kis módosítások

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#219]
Nem  tudom, mikor nyúltok még hozzá az adminhoz... 

Fontossági sorrendben ide írok pár kisebb dolgot, ezek közül az elsőt kérem a fejlesztésben, a többi mehet később, s zárd is le:

-  Hely adatlapon a címkék 3 oszlopos, kategória szerinti  megjelenítése (így nagyon sok a tekerés
- Kiemelés adminban a Hely mellett a címkék kategória szerinti csoportosítása

- A Hely adatlapon a Kiemelés funkció mögé tegyünk egy enyhe háttérszínt, hogy könnyebben megtalálható legyen.

- A Visszajelzések, Érme tranzakciók, Felhasználók listában a frissek legyenek elöl

**Comment by duroakos** [comment]
az egyhszeri rendezés helyett a coin_transaction és a userek közé bekerült a létrevozva oszlop, így lehet arra is rendezni. a többi pedig kész.
