### ISSUE TITLE
Androidon GPS nélkül a címkékre kattintva üresek a távolság szerint rendezett listák

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#221]
**Update:** Megvan a hiba oka.
Androidon, ha a telefonon nincs engedélyezve a tartózkodási hely, akkor a hely címkék listája üres marad. Csak a rating és az akciók száma szerinti lista működik (a listaképek alatti távolság adat nélkül).
A Közelben térképnézet sem zoomol megfelelően Szegedre.
Viszont a Közelben listaszerű nézet rendben megjelenik és a város közepén lévő markerhez igazítja a listát rendező távolságot.

**Javaslat Androidra és iOS-re**: ha nincs engedélyezve a GPS, a user kapjon üzenetet, amikor az első címkére kattint: "Kapcsold be a tartózkodási helyed (iOS-en: helyzeted)! Így tudjuk megmondani, mi van a közeledben!"

Ha elutasítja, kapja rating szerint a listákat (Android és iOS-en is) Utóbbinál most abc szerint kapja.

**Comment by paneksandor** [comment]
Ezt a hibát pénteken 18-19 óra körül észleltem, addig jó ment az app. Utánmagondoltam, milyen helyen nyúltam az adminba, hátha ez hasznos:
A "Testvériség kocsma" hely adminjában kicseréltem a "Szeged, Szabadkai u. 20." címet "Szeged, Szabadkai u 20/b." -ra, mert az elsőt valahol Kiskunfélegyháza körül jelenítette meg a térképen. Mentés után hibaüzenetet kaptam az admin oldalon.

Most két hely is ugyanarra a "Szeged, Szabadkai út 20." címre mutat, és a térképen egymást fedik (ezt írom a módosítanivalók közt, mivel pl. az Árkádban lesznek ilyen helyek).

**Comment by gerezs** [comment]
Itt az Androidoshoz demo video: http://media.delmagyar.hu/ftp/wd/frappe-helymeghat.mp4
