### ISSUE TITLE
Csekkolás, Barátnak küldés

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#226]
A Csekkolás funkció milyen nyomot kell, hogy hagyjon a Facebookon? Lehet, h a beállításaim túl szigorúak, de nekem a appokban sikerült, de a Facebookra nem tudtam megjelentetni a csekkolást.

A Barátnak küldés üzeneteim nem jelentek meg a célzott Facebook oldalakon.

**Comment by tthbalazs** [comment]
A becsekkolás funkció nem jelenik meg Facebookon, mivel ez ott [nem támogatott](https://developers.facebook.com/docs/graph-api/reference/v2.5/checkin).

![checkin](https://cloud.githubusercontent.com/assets/871355/13954427/ff31ee0e-f040-11e5-8f6a-9d8a6d748447.jpg)
