### ISSUE TITLE
A Hely megjelenítése térképen: a hely címét keressük, ne a nevét

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#227]
Pl. 
- a Guttenberg utcában lévő Taj Mahal étterem helyett az agrai Tádzs Mahalt kapom az Apple Maps-en
- a szegedi Gödör étterem Szombathelyen van, a Dock Café La Rochelle-ben

**Comment by tthbalazs** [comment]
Teszteltem néhány lehetséges változatot, és egyedül az bizonyult megbízhatónak, ha a koordinátákat állítom be célként és a keresés teljesen kimarad. Minden más esetben nem egyértelmű a térkép megjelenítése.
