### ISSUE TITLE
listaelemek eltűnő nyitvatartásai (cellaújrahasznosítás)

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#229]
A "Tütü alkoholmentes kocsma" adatlapja és a hozzá tartozó program ("Újjáélesztek egy régi programot az archiválásból") az applikációkban megtalálható, de az adminból eltűnt.

A Tütü címkéi: Étterem, Bisztró, Borozó, Kocsmasportok.

Lehetséges, hogy akkor tűnt el, amikor a hozzá tartozó programot átidőzítettem az Archív zsebből? 
Vagy kitörölte valamelyik tesztelő? De akkor az appokban miért látszik?

A Tütühöz tartozó program ki van emelve, de nem látható a Kiemeltek áttekintésben sem.

**Comment by paneksandor** [comment]
Ide még annyit, hogy a Tütühöz tartozó címkék (Étterem, Bisztró, Borozó, Kocsmasport) listáiban az alábbi jelenség tapasztalható:

Megnyitom az Evés>Étterem listát, görgetek lefelé. 
Egyik-másik listaelem alól lemarad a nyitvatartási információ. 
Ha visszagörgetek a listában, akkor betöltődik, viszont más, újabb helyek alól meg eltűnik. 
Olyan helyekről van szó, amelyeknél rendben meg van adva a nyitvatartás, mindegy, hogy éppen nyitva vagy zárva vannak.
Ha lassan görgetek, akkor is legalább 2 ilyen hiányos elem lesz a listában.

**Comment by duroakos** [comment]
tütü - át lett állítottva budapestire. igy nyilván nem lesz benne a szegedi adminok listájában.

**Comment by paneksandor** [comment]
Köszi! Gondolhattam volna....

Viszont, ez történik az Étterem, Bisztró listában Android Lenovi a606-on és Huawei-en (megy az Adatforgalom és Wifi). Ha le-fel görgetek, mindig más listaelem hagyja el a nyitási infót.
És ez csak azokban a listákban történik, ahol több régióhoz tartozó helyek vannak együtt.

![screenshot_2016-03-16-16-19-23](https://cloud.githubusercontent.com/assets/16239437/13817536/e675f976-eb92-11e5-8528-7888c9d00994.png)


![screenshot_2016-03-16-16-17-06](https://cloud.githubusercontent.com/assets/16239437/13817733/8e6aa82a-eb93-11e5-800d-5ed89c907e55.png)
