### ISSUE TITLE
Egy nappal korábbi nyitvatartás jelenik meg

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#242]
Pl. Evés > Bisztró > 500 ember befér 
helyen látható, hogy vasárnap a szombati nyitvatartás jelenik meg a listában és az adatlapon.

**Comment by tthbalazs** [comment]
Ennél a hibánál sehol nem találtam a kódban arra utaló jelet, hogy rosszul működne, úgyhogy maradt a vasárnapi tesztelés.

Nálam mindenhol jó érték jelenik meg, az 500 ember befér helyen is

![simulator screen shot 10 apr 2016 14 02 21](https://cloud.githubusercontent.com/assets/871355/14410060/1205fb68-ff25-11e5-9a4a-0bc82bc5b3e1.png)
![simulator screen shot 10 apr 2016 14 02 18](https://cloud.githubusercontent.com/assets/871355/14410062/1231de4a-ff25-11e5-9010-d4ec7f9fe8dc.png)
![simulator screen shot 10 apr 2016 14 02 14](https://cloud.githubusercontent.com/assets/871355/14410061/122f0cb0-ff25-11e5-9aac-2e563dd1d4df.png)

**Comment by paneksandor** [comment]
Szia Balázs,
iPhone 5-ön sajnos minden nap az előző nap nyitvatartása jelenik meg.

Az "500 emberen" ma, csütörtökön átírtam a szerdai nyitási időpontot és felfrissítve meg is jelent az éppen látható időpont helyén az adatlapon és a listakép alatt.

Ugyanez van az iPad-emen. Szóval, nem csak vasárnapi jelenség.

**Comment by tthbalazs** [comment]
Az iphone típusának nem kéne számítania. Kérlek próbáld meg letörölni az alkalmazásokat mind a két eszközről, és újból telepíteni. Ha ez sem oldja meg, akkor folytatjuk a keresgélést.

**Comment by paneksandor** [comment]
Szia Balázs, letöröltem és újra telepítettem az ipad-en az appot, és csak megvan a jelenség. Holnap kikérdezem azt a főnököt, akinek iPhone 6-osa van.

Le is fotóztam az appot és az admin beállítást + a dátumot:
![img_0178](https://cloud.githubusercontent.com/assets/16239437/14589383/1e866e7e-04e1-11e6-9ce5-2b00c9845e87.JPG)
