### ISSUE TITLE
A Napfény Kávézoo nem jelenik meg  (ID=255-ös Hely)

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#247]
Lehet, hogy valami trivi probléma, de nem tudok rájönni, miért nem jelenik meg épp ez a hely.

ID= 255, Napfény Kávézoo, egyik címkelistájában sem jelenik meg.

Ivás >Kávézó listában  vagy
Élmény > Ingyen wifi   , Terasz, Egyetemisták    stb listákban kellene lennie

kellene lennie.

**Comment by duroakos** [comment]
![image](https://cloud.githubusercontent.com/assets/1760580/14561963/38b47d2c-031a-11e6-94cf-906134736193.png)

ottvan az.
