### ISSUE TITLE
Április 25-én 5 esetben volt iPhone összeomlás 

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#252]
Nem tudom, ezeket figyelemmel követitek-e az az iTunes Connectben vagy másutt, vagy pedig itt jelezni kell.

**Comment by tthbalazs** [comment]
Ezekről mi kapunk értesítést, csak sajnos az összes crash ugyan az a hiba, amihez nincs elég információnk jelenleg. Összefüggésben lehet a képek túl nagy fileméretével, de még keressük a hibát.
