### ISSUE TITLE
 iOS appban iPhone 5 és iPad4-en az előző napi nyitva tartás jelenik meg.

### ISSUE THREAD

**Issue by duroakos** [DelightSolutions/frappe-feedback#256]

**Comment by paneksandor** [comment]
Újra átnéztem 3 iOS-es eszközön: iPhone6, iPhone 5s, iPad
A hiba ugyanaz, mint amit hetekkel ezelőtt leírtam.

Ezt próbáld ki, pls:
- Egy kiválasztott hely (pl. Cukkini étterem) szerdai zárását átírtam 15 óráról 14 órára.
- Szerda van. 
- Újraindítom a telefont, hogy biztosan frissüljön
- Az eredmény: a listában továbbra is 15 óra van, az adatlapon a becsekkolok gomb fölött 15 óra van, viszont az adatlap alján, a Nyitvatartásnál 14 órára módosult.  

- Most ugyanannál a helynél visszaírom 15 órára a szerdai zárást és a keddi zárást javítom ki 14 órára.
- Szerda van. A frissítés után ez látszik: a listában módosul a mai zárási időpont 14 órára, pedig a keddi (tegnapi) zárási időt módosítottam. Ugyanez történik az adatlapon a becsekkolok gomb fölött. Az adatlap alján viszont a Nyitvatartás alatt a keddi zárás időpontja módosult 14 órára.

Ez azt bizonyítja, hogy a listában és a becsekkolok gomb fölött az előző napi nyitvatartási időpont jelenik meg. Háromféle eszközön.

**Comment by paneksandor** [comment]
Szia Balázs, a mai nap (kedd) folyamán nézd légyszi a  Kávészöm id=235 (kávézó) vagy a Tiszavirág id=242 (étterem) adatlapot a listában. Mindkettő zárva tart hétfőn, de a listában ma, kedden van zárva. Előbbi ma reklamált is. Amit találtam, minden iOS eszközön így néz ki.
