### ISSUE TITLE
iOS-en a listákban zöld nyitva jelzés van zárás után is a helyeknél

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#280]
Hogyan keletkeznek újra ezek a hibák, amiket egyszer már kiteszteltünk?

**Comment by tthbalazs** [comment]
Itt egyelőre csak arra tudok gondolni, hogy a lista még a zárás előtt lett megjelenítve, és a zárás után sem frissült. Tehát pl. megnyitom az Evés > Éttermek listát 17:55-kor, a hely 18:00-kor bezár, majd újból ránézek a listára 18:01-kor. A listaelemek nem frissülnek maguktól, ahhoz el kell tűnniük a képernyőről.
