### ISSUE TITLE
Képek kezelése

### ISSUE THREAD

**Issue by gerezs** [DelightSolutions/frappe-feedback#3]
Képek esetén szüksége lesz majd 
- képcsere és 
- törlés funkcióra, illetve arra, hogy 
- ha több kép van kiválasszuk a nyitó és listanézetekben használt képet.

**Comment by duroakos** [comment]
Ez az issue még régről maradt itt amikor nem volt törlés.
mostmár van. így lehet cserélni is (törlés és új felvétele)
és mostmár van külön listakép feltöltés is.
