### ISSUE TITLE
A galéria melyik képe lesz az adatlap háttérképe

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#34]
Az adatlap adminban feltöltött galériaképek közül jelenleg a fájlnév dönti el, hogy melyik lesz a háttérkép; vagyis nem lehet kiválasztani. Erre kellene módszer, pl. képek sorszámozása.

**Comment by duroakos** [comment]
A galéria képek közül az első az adatlap héttere.
