### ISSUE TITLE
A Szerkesztő ajánlja szöveg a nyitón legyen-e kattintható?

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#35]
Az eddigi teszt userek próbáltak tappolni a Szerkesztő ajánlja szövegre, és elbizonytalanodtak a funkcióban, amikor nem történt semmi. A lapozási funkciót bevallásuk szerint tudják használni akkor is, ha aktív a szöveg.

Mivel ez a link az esetek nagy többségében befelé vezet majd az applikációba, felvetődött, hogy nem lehetne-e aktív a szöveg? Légyszi kérdezzétek meg a UX kollégát, mit szól ehhez.

**Comment by duroakos** [comment]
Ám legyen.

Teszteltük iOS-em hogy mennyire okozna esetleg a odlalragörgetés fals lenyomást. De nem igazán érezzük problémának. Igy a következő release-ben már találkozhattok ezen funkcióval.

Amint androidba is bekerül lezárom a issuet.
