### ISSUE TITLE
Többször is lehet ratingelni egy adatlapot

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#37]
Többször is lehet ratingelni egy adatlapot. Ennek az lehet az eredménye, hogy a tulaj nekiáll és egy éjszaka alatt bebetonozza az 5-ös osztályzatot. 

Tegyük egyedivé a ratinget és adatlaponként egyszer lehessen osztályzatot adni. 

Esetleg lehet, hogy heti 1 alkalommal lehessen újra értékelni a helyet?

**Comment by duroakos** [comment]
Jelenleg egy felhasználó egy adatlapot csak egyszer értékelhet. 
Pontosabban mindig a legutolsó értékelése lesz a mérvadó, hiszen előfordulhat hogy megváltozik a véleményünk egy helyről.

Így nincs lehetőség egy személynek a 5-ös osztályzatra feltornázásra.
