### ISSUE TITLE
Hogyan lehet a Szerkesztő ajánlatát listára, akcióra linkelni?

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#39]
Azt látom, hogy:
frappe://place/tutu
frappe://programe/tacskoverseny

De hogyan lehet hivatkozni
- egy címke listájára? Pl. Evés kategória Pizza címke vagy egy program címke vagy egy akció címke listájára
- egy adott ajánlat listájára?

**Comment by duroakos** [comment]
frappe://list/Kategória/Címke ahol a cimke opcionális
példák:

frappe://list/Evés/Étterem    - ez elvisz egy étterem tagra szűrt evés listába
frappe://list/Akció  - egy akció listát nyit
