### ISSUE TITLE
Lat x Long értékek lekérése

### ISSUE THREAD

**Issue by gerezs** [DelightSolutions/frappe-feedback#4]
Lat x Long mezőknél kellene egy olyan funkció (akár egy külön gomb/ikon), hogy ha a cím be van írva akkor le lehessen kérni a default korrodinátát.
Az adminisztrációt megkönnyítené.

**Comment by duroakos** [comment]
Mostantól minden helynél cím megadásakor/módosításakor automatikusan geokódoljuk azt.
Az így kapott lat/lng értékek továbbra is módosíthatóak kézzel. (Viszont a következő alakalommal ha a cím mező módosul akkor ezek felül íródnak)
