### ISSUE TITLE
Kérdés a programok kezdési dátumáról

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#49]
A program adatlapon egy kezdő és egy végdátum kiválasztása van. 
A kezdő dátummal van kérdésem. Ez a dátum ugye program tényleges kezdési dátuma?  (és nem pedig a program megjelenési dátuma a listában)?

Vagyis, mihelyt egy Program adatlap aktív, akkor ki is kerül a listába. Ha tavasszal kikerül egy nyári program, akkor az a lista alján lesz (hacsak ki nem emelik), és csak akkor kerül fentre, amikor közel van a bekövetkezése.

Ha egy programnak a kezdő és vége dátuma között pl. 1 hét van (fesztivál), akkor az egészen a vége dátumig úgy fog viselkedni, mint ami éppen tart (a lista elején lesz).

Ha pedig letelt a vége dátum, akkor a program lekerül a listából. Az adminban automatikusan inaktívvá válhat és 1 hét után automatikusan törlődhet.

**Comment by duroakos** [comment]
Igen ezt tökéletesen látod.
Annyi kiegészítés hogy nem lesz inaktiv automatikusan. (de a dátum miatt nem jelenik meg a listában.)
