### ISSUE TITLE
Becsekkolok gomb inaktívnak, a címke linknek látszik

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#51]
Ez user teszten jött ki a két alábbi:

A hely oldalon a user váltig tapogatta a szép színes címke gombokat (valóban linkelést remélt tőlük)
Viszont a szürkés "Becsekkolok" és az "Oké, értékelem" gombokat meg olyannak látta, mintha inaktívak lennének.

Ha csak egyiken változtatunk, az utóbbi gombok szövegét tegyük kissé élénkebbé.

**Comment by paneksandor** [comment]
A Becsekkolok gombra, a szöveg elé mehetne  egy kis Facebook ikon azoknak, akiknek nem világos, miről van szó.
Ugyanígy az Értékelem gombra egy csillag ikon.
Ez élénkebbé teszi a gombokat.

**Comment by duroakos** [comment]
gombokra nem tennék ikonokat, mert akkor kellene kb az összesre (qr / beváltás itallap stb..)

de kiemeljük ezen gombokat vizuálisan  valahogy.

a checkin-nél pedig, a jövőbeni félreértés végett nem facebookos checkin. csak frappés. 
azért nem facebookos, mert azt már nem támogatja a facebook sdk. :(

https://developers.facebook.com/docs/graph-api/reference/v2.5/checkin

Publishing of check-ins is deprecated

**Comment by duroakos** [comment]
Így jó lesz?

![1_hely_csekkolasgomb](https://cloud.githubusercontent.com/assets/1760580/13432548/672a9f98-dfce-11e5-86af-5665f1a5a18a.png)

**Comment by paneksandor** [comment]
Így rendben van, köszi
