### ISSUE TITLE
Release note van, app nincs

### ISSUE THREAD

**Issue by gerezs** [DelightSolutions/frappe-feedback#52]
Észrevettem, hogy pénteken elfelejtettétek (?) az iOS appot kitenni.

**Comment by tthbalazs** [comment]
A crashlyticsben én annyit látok, hogy tőletek ketten is telepítették az appot. Nézd meg esetleg a telefonról a weboldalt (vagy az ő mobil appjukat), hátha ott látszik az új verzió.

Este érkezik új build is, remélem annál nem lesz ilyen hiba.

**Comment by gerezs** [comment]
A csatolmányon látszik, h 0219-es bejelentés van, de még nincs hozzá installálható csomag. Erre gondoltam. Persze lehet, h a csomag azonosítóját nem frissítette a kolléga. A lényeg, h eddig egyetlen verzió volt fent, lehet így is akartátok...
![frappeimage](https://cloud.githubusercontent.com/assets/8058830/13214675/6769b31e-d951-11e5-9350-79f15a1bda80.png)

**Comment by gerezs** [comment]
Úgy látszik vmi kompatibilitási issue...
