### ISSUE TITLE
A "Közelben" térkép- és listanézet hibái

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#54]
- A jelenlegi 21 hely és 10 program közül csak 5 hely látható a térképen (2 pesti, 3 szegedi). 
- A Közelben listanézetében a megjelenő helyek sorrendje nem jó, mivel a közeli szegedieknek kellene elöl lenniük, ott pedig 2 pesti vezet (amelyek nincsenek kiemelve)
- A Program ikonok és az Élmény ikonok nem jelennek meg a Közelben térképnézetén.
- A címkés utószűrésnél is hiába választom ki a Program és az Élmény címkét.
Létrehoztam egy helyet, amin csak  Élmény címke van (Szerepjátékos szobaszínház), utóbbit ezzel lehet tesztelni.

**Comment by duroakos** [comment]
Most már csak az 50k- en belüli helyekez adja vissza az API.
