### ISSUE TITLE
Lehetne figyelemfelkeltőbb a "nincs interneted" figyelmeztetés?

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#55]
Az új verzióban minden offline betöltéskor az Android app nyitója jelenik meg a sárga háttérképpel. A telefon ilyen szövegű üzenetet küld: "Ellenőrizze az internet kapcsolatát"
Ezeket az szeretnénk:
- Az offline megnyitott app nyitóján a Szerkesztő ajánlata szöveg helyett jelenjék meg a figyelmeztető szöveg.
- A figyelmeztetés szövege legyen ez: "Jelenleg nincs interneted! Ellenőrizd a kapcsolatod vagy keress hálózatot! Várunk!"
- A figyelmeztető szöveg ne kikapcsolható layer legyen, hanem tartalom helyén jelenjen meg, ezzel is érzékeltetve, hogy nem hibáról van szó, hanem használati adottságról.
- Jelenleg, ha a user offline a kategória gombokra tappol, leáll az app. Itt is meg kellene oldani leállás nélkül, hogy ne hibának élje meg. 
- Ha a user az app használata közben veszti el a wifit, akkor is legyen figyelmeztetése.
- A sárga háttérnek van egy F betűs változata a design képek között. Nem lehetne azt használni? s akkor nincs annyira bedöglött kinézete a net nélküli nyitónak... (a szerkesztő ajánlja kép betöltődése előtt pedig csak rövid ideig látszik).

**Comment by paneksandor** [comment]
Ugye, jól látom, hogy az Android 2-es verzióban minden net nélküli megnyitásnál a nyitót (és nem a legutóbb megnézett oldalt) kapom a figyelmeztetéssel? Ha igen, így jól van.

Ha a figyelmeztetés ellenére kattintok, akkor leállási üzenetet kapok. Ha visszagombbal visszalépek, akkor el tudok jutni korábban megnézett oldalakra. Lehetne, hogy a figyelmeztető layert mindig megkapja a user, ha net nélkül korábbról eltárolt oldalakat néz az appban?

**Comment by duroakos** [comment]
![0_nointernet](https://cloud.githubusercontent.com/assets/1760580/13432525/4d762cde-dfce-11e5-88e0-088bd5ed983e.png)

**Comment by paneksandor** [comment]
Az üzenet megoldása rendben van. 
Ez az ablak ugye, megjelenik, akármelyik oldalra érkezik meg a net nélküli user?

Mi történik ebben az esetben:
A user WiFi-vel használja az appot, majd félbeszakad a kapcsolat. Kapja a figyelmeztető ablakot. Hiába nyomogatja az újra próbálkozom gombot, ha nincs net és ez mindig visszatér. Lehetne egy "OK" gombot tenni a bal alsó sarokba (vagy egy x-et a jobb felsőbe) amivel lezárhatja az ablakot és nézheti azt, ami eltárolódott a cache-ben? 

Ezt a szöveget kérjük:

(!) **Hoppá! Nincs neted!**
Csatlakozz WiFi vagy mobilhálózathoz! 
Az app megfelelő működéséhez erre szükség van.
Várunk vissza!
                                      ÚJRA PRÓBÁLKOZOM

**Comment by duroakos** [comment]
Mint már sokszor írtam nicns offline működés. így nem kell az oké.
és semmit nem fogunk a cacheből megjeleníteni.

**Comment by paneksandor** [comment]
Balázsnak van egy kommentje a töredezett net problémára, amivel egyetértettünk.  #79
Erre gondoltam. 
Mi történik, ha 1 percre elmegy a wifi? A user néz egy oldalt, eközben kap egy figyelmeztető ablakot és addig tapogathatja, amíg újra nincs Wifi? Még azokat az oldalakat sem tudja nézni, amelyeket már letöltött? Még azt sem, amit éppen nézett, amikor eltört a wifi?
