### ISSUE TITLE
Az utószűrési listához jutás könnyítése

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#56]
A #48 issueban jeleztem, hogy a Program lista oldalán fölösleges a listarendezést külön menüpontnak venni, mert csak egyféle rendezés van. 

 Én az Evés, Ivás és Élmény listaoldalon is soknak tartom azt, hogy két lépésben kell eljutni egy olyan fontos funkcióhoz, mint az utószűrés. A Közelben oldalon lévő megoldást tartanám jónak, 
![kkko](https://cloud.githubusercontent.com/assets/16239437/13232659/6fa78ba0-d9b0-11e5-840f-56f0573e4eb8.JPG)
ahol a listarendezésnek és az utószűrésnek külön ikonja van. Látom, hogy az Evés/Ivás/Élmény oldalakon keresési ikon is van. Nem lehetne-e a Keresés és a Rendezés funkciókat lenyílóba tenni, és az utószűrést önálló címke ikonnal kitenni? 

Így a Közelben, a Program és az Akció oldalakkal következetes lesz az utószűrés helye.

**Comment by duroakos** [comment]
A program listáról leszedjük a rendezést (valóban nem sok értelme).
De a keresést nem szeretnénk eltenni onnan, hiszen az actionbarba nyilik a keresősáv.
Továbbá pontosan hogy a címke utószűrő aminke a helye mindig következetes.
 a #48 as issueval viszont foglalkozunk.
