### ISSUE TITLE
A program adatlapon legyen opcionális a vége dátum megjelenítése

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#58]
Egy programra nagyon jellemző a kezdési dátuma, de sokkal ritkábban a vége dátum is. 
Pl. egy koncert vége dátumát nem is tudjuk.

A program adatlapján azonban a cím alatt mindenképpen megjelenik a vége dátum, akkor is, ha a adminban nincs megadva (esetemben: törölve van). --> Mondanám, hogy hagyhassuk üresen a vége dátum mezőt, de akkor a program nem tud inaktiválódni és törlődni. A  megoldás talán az, hogy legyen opció: megjelenjen-e. Pl. egy többnapos fesztiválnál érdekes, mikor van vége.
(És a naptárba sem kell betenni a vége dátumot.)

Van olyan eset is, amikor a kezdő dátumra nem jellemző a kezdési óra:perc, mert egész napos a program (pl. egynapos fesztivál). --> Lehetne, hogy csak a dátum részt adjuk meg?

És van olyan is, amikor periodikusan ismétlődő programról van szó, amit nem lenne jó újra és újra felvinni. Pl. minden szombaton 20 órakor vodka buli. Ilyenkorra jó lenne egy, a hét adott napjára beállítás ? (de ez csak nice to have)

**Comment by duroakos** [comment]
mostmár adminon lehet beállítani hogy opcionális a vége dátum.

az alkalmazásokban akkor ha ez opcionális akkor nem jelenik meg sem a listában, sem az adatlapon.
Ez így jó lesz?

A többi kérés jelen API ban nem kivitelezhető extra fejlesztés nélkül.
