### ISSUE TITLE
Push üzenet targetálása belső oldalakra

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#61]
A push kiküldési terveinkben az szerepel, hogy a kiküldött értesítésről az appon belül **adott oldalra** tudjuk eljuttatni a usert. Ilyen oldalak lehetnek pl. a lent soroltak. Ehhez azonban (akárcsak a bannernél) céloldalt kell tudnunk adni. Látom, hogy van Push target modul kiválasztás, de ennek a jelenlegi opciói nem fedik a konkrét oldalakat. (Vagy mit is tud ez a select?)

Szóval, ha tudjuk a belső elérés címét (pl. frappe://place/tutu ), akkor ezt egy mezőbe beírhatnánk.

- A legjobb fagyizók Szeged --> Az Evés kategória "fagyizó" címke listájára visz
- Este BL-meccs! Itt nézheted kocsmában! --> Az Élmény kategória "meccsnézés" címke listája
- Itt a borfesztivál programja --> Egy adott program adatlapra visz 
- Új akciókat kaptál a Frappéban --> A user Akciók listájára visz
- Ettől a helytől fejre állsz --> Egy adott hely oldalára visz
- Térképen az összes nyári program! --> A Közelben térképes nézet Program-ra szűrt oldala
- Így ihatsz ingyen sört! --> Egy adott akció oldala

Pusztán annyi nem elég vonzó, hogy "Nézz be az Evás kategóriában, mert valahol ott vannak a fagyizók"

**Comment by duroakos** [comment]
frappe://list/Kategória/Címke ahol a cimke opcionális
példák:

frappe://list/Evés/Étterem - ez elvisz egy étterem tagra szűrt evés listába
frappe://list/Akció - egy akció listát nyit
