### ISSUE TITLE
Push üzenet engedélyezése kategóriákra?

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#62]
Ez egy kérdő hangsúllyal előadott kérés :)
Ha az adminban meg tudjuk határozni a Push target modult, akkor nem tudnánk a Push engedélyezési helyen is felajánlani, hogy a user válasszon, melyik területről szeretne értesítéseket kapni?

**Comment by duroakos** [comment]
Az adminban a push target modul az még anno teljesen más miatt került be (a target mező egyik részeként), de azóta felkészítettük az appokat hogy targetnek akár lista is megadható lehessen.

De még több push beállítással nem igazán traktálnánk a usert.
Illetve a push logikát is erőteljesen megvariálná, ezt nem javasoljuk jelenleg, de ha valami elegánsabb és gyorsabban kivitelezhető megoldás jut eszünkbe menet közben, nem fogjuk magunkban tartani.
