### ISSUE TITLE
Csak a programok miatt felvett helyek

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#65]
Számos programhelyet fel lehet venni az Evés, Ivás, Élmény kategóriába, de azért lesznek olyan helyek, amelyek furán néznek ki ezekben a listákban.

Pl. a borfesztivál a Széchenyi téren van, de a Széchenyi tér nevű adatlap nem fér egyik kategóriába sem.

**Lehet-e úgy felvenni helyet, hogy nem választunk ki egyik Kategóriát sem hozzá?** Ez esetben ez a hely nem lesz elérhető a címkés szűrésekben, csak  a szabad szavas keresés mutatja meg őket. 

Azonban ezeket a helyeket is be kell tudni tallózni a program adminban.

**Comment by duroakos** [comment]
Ez így elméletileg megvalósítható. 
Viszont a keresés sem adná ki, hiszen ott kategórián belül keresünk.
Így totálisan be lehet tallózni programhoz.
