### ISSUE TITLE
A keresési mező prediktív jellege

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#66]
Meg tudnátok úgy oldani a szabad szavas keresést, hogy 2-3 betű beírása után egy prediktív lista legyen a találati oszlopban? Talán így könnyebb mobilon keresni, mint a teljes szó beírásával...

A keresési szöveg beíró klaviatúrája nem tűnik el a keresés jóváhagyása után (csak visszagombbal vagy kilépéssel)

Meg tudjátok úgy oldani, hogy a keresés találati listáján ne legyen banner?

**Comment by duroakos** [comment]
A prediktív kereső mező olyan mértékű extra fejlesztés lenne amit hibajavítás vagy support keretében sem tudunk megvalósítani.

A billentyűzet működése oprendszer adottság, de megnézzük hátha lehet valamit kezdeni mégis vele.

A lista pedig ugyanaz a lista mint a normál lista, éppen ezért ezt nem tudjuk sajnos megoldani. (extra fejlesztés nélkül)
