### ISSUE TITLE
Hová jutsz vissza, amikor újra megnyitod az appot?

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#67]
Ez az elgondolásunk:
- Ha a user kilép (másik appot használ, telefonál) és a kilépése 1 óránál tovább tart, akkor a nyitóra hozzuk vissza az új session-ben.
- Ha a user 1 óránál kevesebbet marad távol, akkor ott kezdje az új sessiont, ahol abbahagyta legutóbb. (Ha közben frissült az oldal, akkor lehet neki ugyanazt az oldalt frissíteni?)

Jelenleg az van, hogy ha a usernek nincs elég memóriája a telefonban (pl. nekem nincs), akkor pár másodperc után is már a nyitóra visz vissza. Ha viszont van elég memória, akkor másnap is az előző session oldala fogadja.

Sejtem, hogy kevés memória esetén is meg lehet oldani, hogy (online) visszatöltődjön a legutóbb nézett oldal (de ez inkább kérdés).

**Comment by duroakos** [comment]
Sajnos ez a témakör nem annyira kontrollálható, mint elsőre gondolnánk.
Az app normális esetben oda tér vissza megszakítás utén a mint ahol addig is volt.

Viszont semmi nem garantálja hogy a memóriában marad, mert a rendszer automatikusan felszabadíthat helyet az éppen előtérben lévő alkalmazás javára és ez eredményezheti azt hogy az állapot már nem elérhető. Ez a működés androidon teljesen ismerős android felhasználóknak.

Visszatölteni az állapotot meg nem tartom szerencsésnek, hiszen nem cska egy adatlapról beszélünk, hanem a teljes navigációs strukturáról. És ha menet közben valami változott (pl egy tag inaktív lett, vagy már nem aktuális a program) akkor könnyen olyna állapotba futhat az alkalmazás amire nem biztos h fel van készítve.
