### ISSUE TITLE
Tizedescsillag az összesített rating megjelenítésében

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#68]
A hely adatlapon a kép alatti ratingcsillagok vehessenek fel tizedesjegyet is tükröző állapotot, vagyis a sorban az utolsó csillagnak csak bizonyos hányada látsszon kitöltött állapotban.

**Comment by duroakos** [comment]
Mivel a kijelzők függvénynében kellene egyedileg ezt a bizonyos hányadot számolni és amugy is esztétikaliag aggályos ez a kérés, hiszne ha csak pl 3.2 a rating akkor egyötödnyi csillag inkább valami vizuális problémának tünne.

és amugy sem lenne ott szimmetrikus a nézet emiatt. a látvány tervekben sem véletlenül nem szerepel törtcsillag.

**Comment by paneksandor** [comment]
Jól van, értem, hagyjuk.

A ti korábbi válaszotok alapján írtam be (utolsó designt érintő lista), de nem érdekes, esztétikailag valóban nem jó.
