### ISSUE TITLE
Karakterszám jelzés

### ISSUE THREAD

**Issue by gerezs** [DelightSolutions/frappe-feedback#7]
Az adatlapok cím beíró mezőjében legyen jelzés, hogy hány karakter fér a listában az ajánlóra, ill. az adatlapra.

**Comment by duroakos** [comment]
Erre kérnék a tesztelésetek alapján számokat hogy mennyire vegyen és hol a limitet.

**Comment by gerezs** [comment]
(hely, program és akció) Név: 45
rövid név: 25
Itt nem hiszem, h limitálnunk kellene, legfeljebb jelezni/visszazámolni (csak ki kell jeleznünk, nem megakadályoznunk)
