### ISSUE TITLE
Hely adatlapnál kontakt ikonok

### ISSUE THREAD

**Issue by gerezs** [DelightSolutions/frappe-feedback#71]
A térkép ikon nem aktív ( pedig van lat long érték), telefon nem tapolható, és Facebook oldal ikonja sem tapolható.

**Comment by duroakos** [comment]
iOS?

**Comment by gerezs** [comment]
Ahha, - bocs, h kimaradt.

**Comment by tthbalazs** [comment]
A térkép ikon valóban nem aktív, ez a következő verzióban már az lesz.

A többi ikon biztosan tapolható, a telefon iOS oldalon sajnos nagyon kényes a formázásra ezért előfordulhat, hogy nem hívja a számot.

A többi ikon pedig szerintem csak nagyon pici, megpróbálom nagyobbra venni őket. Pl. a facebook esetében *pontosan* az f-re kell nyomni, amit ujjal valóban elég nehéz
