### ISSUE TITLE
Hely címke háttérszíne túl világos

### ISSUE THREAD

**Issue by gerezs** [DelightSolutions/frappe-feedback#72]
Ha megnézed a Rongy-kocsma A hely címkéi résznél a 'Zenés hely', és 'Olcsón' címkék háttere túl világos.

**Comment by tthbalazs** [comment]
Ezek a címkék az adott pillanatban nem tartoztak semmilyen kategóriához, ezért egy szürke színt kaptak csak háttérként. Most már megjelenik a háttér színe is, de az ilyen esetek elkerülése végett sötétebbre vettem a címkék hátterét.

**Comment by gerezs** [comment]
Kösz!
