### ISSUE TITLE
Listaelem - egy szöveghossznál az alsó sor csak félig látszik

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#73]
A listaelemben a hely Név szöveg hosszúságától függően lehetséges olyan állapot, hogy az alsó sor csak félig látszik. Ez akkor jön elő, ha az alsó sorban éppen kifér a szó.

![eeer](https://cloud.githubusercontent.com/assets/16239437/13283762/0d7c0a1e-daf0-11e5-9b76-a039340fa9fb.JPG)

másik példa:

![eeeet](https://cloud.githubusercontent.com/assets/16239437/13283763/130fa4fe-daf0-11e5-85f6-0ae337e45ea6.JPG)

**Comment by duroakos** [comment]
Ezt nem gondolnám, hibának. Hiszen ilyen hosszúságú címre nem kellene amugy sem készülni.

Inkább akkor várom az inputot, hogy a tesztek alapján milyen hosszúságra limitáljuk a felvehető helyek, programok, akciók neveit.

**Comment by paneksandor** [comment]
A cím hosszúságának megoldása szerintem jól van így, ne korlátozzuk. A "Minden szöveg iszonyú hosszú..." nevű hely adatlapja (Evés>Bisztró lista) jól mutatja, hogy egy baromi hosszú szöveg is jól megjelenik!
Én már ezzel elégedett voltam.
Ehhez képest a jelzett anomáliát ki lehet kerülni más szövegezéssel, csak azért írtam fel, hátha van egyszerű megoldásod.

**Comment by duroakos** [comment]
Nem sajnos nincsen, mert sajnos más-és más kijelzőarányokon máshol törhetnek a címek és máshogy méreteződnek.
