### ISSUE TITLE
Kötegelten feltölthető teszt adatbázis 99 elemmel

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#74]
Itt küldöm:

[kotegelt-feltoltes-tabla-99-kuld.xlsx](https://github.com/DelightSolutions/frappe-feedback/files/144570/kotegelt-feltoltes-tabla-99-kuld.xlsx)

Szóljatok, ha még piszkálni kell.

Ezt csak a teszt miatt küldöm, majd, ha az adatbázis végleges lesz, akkor légyszi azt is töltsétek fel kötegelten. Ugyanezek az oszlopok és szabályok lesznek benne.

Az itt feljuttatott helyekhez a default fotók járulnak majd, ha jól gondolom.

**Comment by duroakos** [comment]
Annyi  probléma van hogy a nyitva/zárva tartást nem szövegként veszitek fel, hanem időként.
Légyszi legyen madj szöveg. (A meglévőeket gyorsan úgy lehet szöveggé tenni hogy kiejlölöd az összeset kimásolod notepadbe, excelben a cellák tipusat szövegre állítjátok aztán a notepadból visszamásoljátok speciális beillesztéssel)

De most megcsináltam illetve fel is töltöttem h élesen is megy.

Ment. mint ahogy láthatjátok.

[kotegelt-feltoltes-tabla-99-kuld (1).xlsx](https://github.com/DelightSolutions/frappe-feedback/files/160030/kotegelt-feltoltes-tabla-99-kuld.1.xlsx)


Örülnék egy min 10 db-os program.xlsx-nek is.

**Comment by paneksandor** [comment]
Szia Ákos, köszi, vettem: a nyitva/zárvatartás szöveg lesz. 
A programra visszatérek rövidesen.
