### ISSUE TITLE
Mit tesz a telefon ikon, ha nincs sim kártya a telefonban?

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#77]
A telefon kiemelés ikonra tappolásra akkor kezdeményezzen hívást, ha sim kártya is van a mobil eszközben. Ha nincs, jelenítsük meg a telefonszámot.

**Comment by duroakos** [comment]
az ikonra rányomva amugy is átdob az a telefon alapértelmezett tárcsázójába, ahol látszik a telefonszám. És a tárcsázó már gondoskodik arról hogy ha nincs SIM.
