### ISSUE TITLE
Az oldalak cachelése

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#79]
Szia Ákos, a használat közben elment netes kapcsolat problémájáról a Lapcom vezető fejlesztőjét is megkérdeztem, ill. megkértem, hogy teszteljen. Az alábbi  issue-ban javaslat is van. A cél, hogy ami oldalakat letöltött a user, azok maradjanak is meg a telefonján.

Majzik Mátyás vezető fejlesztő:
A probléma: kiválasztok egy címkét, pl.: étterem. Behozza az éttermek listáját. Ha ilyenkor elmegy a netem, vagy leáll a szerver, akkor ha visszalépek főoldalra vagy android kilövi az appot, mert másik alkalmazást használunk ideiglenesen ami sok memóriát igényel, onnantól újra az étteremre kattintva nem jön találat. 

A megoldás: általánosan meg kell oldani, hogy minden kérést cache-eljenek az appok, ezáltal akár pillanatnyi/hosszabb net kiesést is tudna tolerálni, valamint csökkenti a terhelést a back-end rendszeren, de a legfontosabb, csökkenti a net forgalmat a felhasználónak.

Ezt legegyszerűbben úgy lehet megoldani, hogy egy un cache layert kell betenni a kommunikációs réteg és a back-end szerverek közé az appokban implementálva.
Tehát minden lekérés a backend felé átmegy ezen a cache layeren, amely megnézi hogy van-e már ilyen kérés, ugyanebben a formában cache-ben, ha igen és nem túl régi (pár perc) akkor onnan szolgálja ki, nem fordul a back-end szerverekhez. Ha nincs természetesen, akkor megpróbálja onnan és utána el is menti cache-be, hogy következő lekérésnél meglegyen. Ha nincs net automatikusan megpróbálja cache-ből kiszolgálni, akkor elévülési idő nincs. 

Ezzel az egyszerű módszerrel lehet fokozni a felhasználói élményt, csökkenteni a netforgalmat és nem kell hozzá az appokat megbolygatni, relative kevés fejlesztéssel megoldható, hisz pont ezért transzparens ez a réteg, hogy nem befolyásolja alatta az eredeti megvalósítást.

Erre már könnyen egy egyszerű lépéssel megoldható az, hogy az app első olyan induláskor, amikor van net, kérje le az összes címke találatait. Nem kell vele kezdjen semmit, de így a cache réteg, eltárolja, tovább növelve a felhasználói élményt, hisz ha akár képek nélkül is, de lesznek mindenhol találatok.

Persze igazi az lenne ha lenne offline működés, mert ez nem ad megoldást lapozásokra és olyan tartalmakra amiket eddig nem nézett (kivéve ha címkéken végigszalad első induláskor).

**Comment by tthbalazs** [comment]
Az egyes kérések cachelése a hálózati keretrendszer része ami figyelembe veszi a szerver által küldött `Cache-Control`, `Last-Modified` és `Etag` headert, és annak megfelelően cselekszik.

Ezt a tulajdonságát a fejlesztés és a tesztelés során **tudatosan nem használjuk** a gyakori változtatások miatt, illetve a könnyebb tartalom ellenőrzés érdekében.

**Comment by gerezs** [comment]
Balázs, ez azt jelenti, hogy akkor a tartalom cachelődni fog?
Milyen szintig? Minden oldal és lista amit egy adott esetben megnézünk akkor az ha épp megszakad a net, még megnézhető lesz, ugye?

**Comment by tthbalazs** [comment]
Úgy gondolom egy rövid magyarázat kelleni fog a válaszomhoz.

A cache működése függ a szervertől és a klienstől egyaránt. Ha a szerver az adott tartalomra azt mondja, hogy ez a tartalom 5 percig tekinthető frissnek, akkor a kliens a következő 5 percben fogja a cacheben tárolt verziót használni. Ezt követően megy csak kérés a szerverhez. 
Ehhez hasonlóan ha a szerver egy adott tartalomra azt mondja, hogy ez a tartalom nem cachelhető, akkor a kliens soha nem fogja tárolni.

Azt, hogy a kliens mennyi adatot tárolhat a cacheben nekünk kell meghatározni. Két fajta cachet használ a rendszer: lemezen és memóriában tároltat. HA az általunk letöltött tartalom a memóriába kerül, akkor az onnan bármikor törlődhet (az operációs rendszer kifejezetten jelezheti az alkalmazások számára, ha memóriára van szüksége. Ilyenkor az ehhez hasonló gyorsítótárak tartalma megy a kukába elsőnek). Ha törlődik a tartalom, akkor hiába mondtuk meg, hogy ezt 5 percig tárolni kell, sajnos nem lesz elérhető.
Az ilyen elkerülése végett szokás a lemezen tárolt gyorsítótárat is használni ami lassabb, de nagyobb esélyünk van a cache tényleges jelenlétére. Azért mondom csak azt, hogy nagyob esélyünk van, mivel a cache méretéből adódóan a régebbi elemeket innen is kidobhatja a rendszer, hogy az újabb elférjen.

Amit én befolyásolni tudok az a **cache mérete**, illetve a szerver által visszaadott **cache időtartam**.

Megfelelő beállítások mellett (elég nagy cache, elég hosszú cache időtartam) jó esély van arra, hogy a cachelt tartalmak megjelenhetnek ha megszakadt az internet kapcsolat.

> Milyen szintig?

Minden szerver felé irányuló kérés részese a cache folyamatnak, a végső beállítások ismerete nélkül ezt nehéz megmondani.

> Minden oldal és lista amit egy adott esetben megnézünk akkor az ha épp megszakad a net, még megnézhető lesz, ugye?

Példa:

Frissen indított appban (üres cache) kiválasztom az Evés kategória Étterem címkéjét, megnézek 1-2 helyet majd visszamegyek a menübe.
Megszakad az internet kapcsolat. 
-> Megint kiválasztom az Evés kategória Étterem címkéjét: a tartalom nagy valószínüséggel megjelenik. (Függ a kapott válasz és a cache méretétől)
-> Ha az Evés kategória egy másik címkéjét választom, akkor a tartalom már biztosan nem fog megjelenni, még ha vannak a két listában közös helyek akkor sem. (Mivel nem volt még ilyen kérés a cacheben tárolva)

Ez így nagyjából rendben van?

Még egy apróság: 
A cachelés nem összekeverendő az offline működéssel. A cachelés csak a "darabos" internet kiküszöbölésére, és a felesleges adatforgalmazás elkerülésére van.

_Megjegyzés: Ha én írok bárhova választ akkor azt tekintsétek az iOS verzióra igaznak, Androidban én nem vagyok járatos._

**Comment by gerezs** [comment]
Kösz Balázs, örülünk, hogy így leírtad, ez így tiszta. 
A cache vs offlinet (nagyjából) értettük, csak a cache-elt oldalakra akartunk egy választ (ezt ugyanígy meg fogják tőlünk kérdezni és nem akartuk, h a technológia bonyolultsága legyen a válasz, és a válasszal együtt azt szem előtt fogjuk tartani, h a készülék memóriája és tárhelyétől is függ, mi érhető el.) 
Kimondottan ezt szeretnénk amit írtál: A cachelés csak a "darabos" internet kiküszöbölésére, és a felesleges adatforgalmazás elkerülésére van.
