### ISSUE TITLE
Címkeszöveg ikon eltolódása

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#84]
A címke lista oldal menu barban a Címkeszöveges ikon mintha egy kicsit jobbfelé lenne tolódva, de lehet, h rosszul látom. Ha igen, légyszi igazítsuk a vissza nyíl mellé, balra.

**Comment by tthbalazs** [comment]
Csináltam a szimulátorban egy képet, hogy hogyan nézne ki balra tolva:
![simulator screen shot 09 mar 2016 11 30 56](https://cloud.githubusercontent.com/assets/871355/13632603/c1193826-e5ea-11e5-8187-9d7bc094fa95.png)

Ennél jobban sajnos nem tudom balra vinni a címkét, mert a vissza gomb a nyílméreténél valójában sokkal nagyobb, ahogy az alábbi képen is látszik:
![backbuttonframe](https://cloud.githubusercontent.com/assets/871355/13632602/c0ef164a-e5ea-11e5-99ad-d8ceba9bb8ec.png)

A gyári vissza gomb méretét sajnos nem tudom megváltoztatni, úgyhogy ezek az adottságok. Ha ebben a pozícióban tetszik akkor átmozgatom, de szerintem középre igazítva rendezettebbnek tűnik.

**Comment by tthbalazs** [comment]
Erre tudtok mondani valamit? Mert a képeket javítjuk, és hamarosan küldenék egy új verziót, amiben ez is benne lehet, ha szükséges.

**Comment by paneksandor** [comment]
Köszi, igazad van, maradjon középen
