### ISSUE TITLE
Nincs rajta a címke, mégis megjelenik a listában

### ISSUE THREAD

**Issue by paneksandor** [DelightSolutions/frappe-feedback#97]
Az iOS Ivás>Bulihely listában benne van a 400 Bar nevű hely, noha nincs rajta a Bulihely címke és nincs kiemelve sem.

Ez a #85 és #86 issue-kkal függhet össze.

**Comment by tthbalazs** [comment]
Igen azokkal, és javítva is van a következő verzióban.
